site_name: Il Paesaggio archeologico dell'Asia Occidentale Antica
site_url: https://andreatitolo.github.io/gislab2023/
site_author: Andrea Titolo
site_description: >-
  Sito del laboratorio studenti 'Il Paesaggio archeologico dell'Asia Occidentale Antica'

# Repository
repo_name: andreatitolo/gislab2023
repo_url: https://github.com/andreatitolo/gislab2023

theme:
    name: 'material'
    favicon: Assets/satellite-variant.svg
    icon:
      repo: fontawesome/brands/github
      logo: material/satellite-variant
    features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - toc.follow
    - content.code.annotate
    - content.tooltips
    - search.suggest
    - search.highlight
    - search.share
  
    palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  - admonition  
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 
  - mermaid2

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
